version: "3.9"
services:
  webapp: 
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - type: bind
        source: .
        target: /home/node/src
